//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLib.Resx {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResStr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResStr() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceLib.Resx.ResStr", typeof(ResStr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 SCUNET campus network auto login tool 的本地化字符串。
        /// </summary>
        public static string Appname {
            get {
                return ResourceManager.GetString("Appname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto login failed. 的本地化字符串。
        /// </summary>
        public static string AutoLoginFailed {
            get {
                return ResourceManager.GetString("AutoLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto login successful. 的本地化字符串。
        /// </summary>
        public static string AutoLoginSuccess {
            get {
                return ResourceManager.GetString("AutoLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Details: 的本地化字符串。
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Already logged in 的本地化字符串。
        /// </summary>
        public static string ErrAlreadyLoggedIn {
            get {
                return ResourceManager.GetString("ErrAlreadyLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login failed: {0} 的本地化字符串。
        /// </summary>
        public static string ErrLoginFailedFormat {
            get {
                return ResourceManager.GetString("ErrLoginFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MAC address not found in query string 的本地化字符串。
        /// </summary>
        public static string ErrMissingMacAddress {
            get {
                return ResourceManager.GetString("ErrMissingMacAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redirect location is missing ({0}) 的本地化字符串。
        /// </summary>
        public static string ErrMissingRedirectLocationFormat {
            get {
                return ResourceManager.GetString("ErrMissingRedirectLocationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modulus must be a positive hexadecimal value. 的本地化字符串。
        /// </summary>
        public static string ErrModulusNotPositiveHex {
            get {
                return ResourceManager.GetString("ErrModulusNotPositiveHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trigger risk control 的本地化字符串。
        /// </summary>
        public static string ErrRiskControlTriggered {
            get {
                return ResourceManager.GetString("ErrRiskControlTriggered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Too many users online 的本地化字符串。
        /// </summary>
        public static string ErrTooManyUsersOnline {
            get {
                return ResourceManager.GetString("ErrTooManyUsersOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected redirect location: {0} 的本地化字符串。
        /// </summary>
        public static string ErrUnexpectedRedirectFormat {
            get {
                return ResourceManager.GetString("ErrUnexpectedRedirectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported service: {0} 的本地化字符串。
        /// </summary>
        public static string ErrUnsupportedServiceFormat {
            get {
                return ResourceManager.GetString("ErrUnsupportedServiceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hotspot Started 的本地化字符串。
        /// </summary>
        public static string HotspotStarted {
            get {
                return ResourceManager.GetString("HotspotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hotspot Start Failed 的本地化字符串。
        /// </summary>
        public static string HotspotStartFailed {
            get {
                return ResourceManager.GetString("HotspotStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login failed for user {0}: {1} 的本地化字符串。
        /// </summary>
        public static string LoginFailedForUserFormat {
            get {
                return ResourceManager.GetString("LoginFailedForUserFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No user configured 的本地化字符串。
        /// </summary>
        public static string NoUserConfigured {
            get {
                return ResourceManager.GetString("NoUserConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SCUNET Wifi Connected 的本地化字符串。
        /// </summary>
        public static string SCUNETWifiConnected {
            get {
                return ResourceManager.GetString("SCUNETWifiConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SCUNET Wifi Connect Failed 的本地化字符串。
        /// </summary>
        public static string SCUNETWifiConnectFailed {
            get {
                return ResourceManager.GetString("SCUNETWifiConnectFailed", resourceCulture);
            }
        }
    }
}
