//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sal.GUI.Resx {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResUI() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sal.GUI.Resx.ResUI", typeof(ResUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        public static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect SCUNET WiFi 的本地化字符串。
        /// </summary>
        public static string CbConnectSCUNETWifi {
            get {
                return ResourceManager.GetString("CbConnectSCUNETWifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Hotspot 的本地化字符串。
        /// </summary>
        public static string CbEnableHotspot {
            get {
                return ResourceManager.GetString("CbEnableHotspot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 China Mobile 的本地化字符串。
        /// </summary>
        public static string LbChinaMobile {
            get {
                return ResourceManager.GetString("LbChinaMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 China Telecom 的本地化字符串。
        /// </summary>
        public static string LbChinaTelecom {
            get {
                return ResourceManager.GetString("LbChinaTelecom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 China Unicom 的本地化字符串。
        /// </summary>
        public static string LbChinaUnicom {
            get {
                return ResourceManager.GetString("LbChinaUnicom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 edunet 的本地化字符串。
        /// </summary>
        public static string LbEdunet {
            get {
                return ResourceManager.GetString("LbEdunet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initial Delay (ms) 的本地化字符串。
        /// </summary>
        public static string LbInitialDelayMs {
            get {
                return ResourceManager.GetString("LbInitialDelayMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string LbMessage {
            get {
                return ResourceManager.GetString("LbMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string LbPassword {
            get {
                return ResourceManager.GetString("LbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remark 的本地化字符串。
        /// </summary>
        public static string LbRemark {
            get {
                return ResourceManager.GetString("LbRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retry Count 的本地化字符串。
        /// </summary>
        public static string LbRetryCount {
            get {
                return ResourceManager.GetString("LbRetryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retry Delay (ms) 的本地化字符串。
        /// </summary>
        public static string LbRetryDelayMs {
            get {
                return ResourceManager.GetString("LbRetryDelayMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service 的本地化字符串。
        /// </summary>
        public static string LbService {
            get {
                return ResourceManager.GetString("LbService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username 的本地化字符串。
        /// </summary>
        public static string LbUsername {
            get {
                return ResourceManager.GetString("LbUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login successful! 的本地化字符串。
        /// </summary>
        public static string MsgLoginSuccess {
            get {
                return ResourceManager.GetString("MsgLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No VM provided 的本地化字符串。
        /// </summary>
        public static string MsgNoVmProvided {
            get {
                return ResourceManager.GetString("MsgNoVmProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VM Not Registered: {0} 的本地化字符串。
        /// </summary>
        public static string MsgViewModelNotRegistered {
            get {
                return ResourceManager.GetString("MsgViewModelNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config 的本地化字符串。
        /// </summary>
        public static string NavConfig {
            get {
                return ResourceManager.GetString("NavConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        public static string NavLogin {
            get {
                return ResourceManager.GetString("NavLogin", resourceCulture);
            }
        }
    }
}
